myproject/urls.py
from django.urls import include, path
from myproject.bands import views as v
from django.contrib import admin

app_name = 'bands'

urlpatterns = [
    path('', v.home, name='home'),
    path('bands/', v.band_list, name='bands'),
    path('bands/<int:pk>/', v.band_detail, name='band_detail'),
    path('bandform/', v.BandCreate.as_view(), name='band_form'),
    path('memberform/', v.MemberCreate.as_view(), name='member_form'),
    path('contact/', v.band_contact, name='contact'),
    path('protected/', v.protected_view, name='protected'),
    path('accounts/login/', v.message),
    path('admin/', admin.site.urls),
]

myproject/bands/models.py
from django.db import models
from django.urls import reverse_lazy


class Band(models.Model):

    """A model of a rock band."""
    name = models.CharField(max_length=200)
    can_rock = models.BooleanField(default=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'band'
        verbose_name_plural = 'bands'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # retorna a url no formato /bands/1/
        return reverse_lazy('band_detail', kwargs={'pk': self.pk})

    def get_members_count(self):
        # count members by band
        # conta os membros por banda
        return self.band.count()


class Member(models.Model):

    """A model of a rock band member."""
    name = models.CharField("Member's name", max_length=200)
    instrument = models.CharField(choices=(
        ('g', "Guitar"),
        ('b', "Bass"),
        ('d', "Drums"),
        ('v', "Vocal"),
        ('p', "Piano"),
    ),
        max_length=1
    )

    band = models.ForeignKey(
        "Band",
        related_name='band',
        on_delete=models.CASCADE
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return self.name

myproject/bands/forms.py
from django import forms
from .models import Band, Member


class BandContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class BandForm(forms.ModelForm):

    class Meta:
        model = Band
        fields = '__all__'


class MemberForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = '__all__'

myproject/bands/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .models import Band, Member
from .forms import BandContactForm, BandForm, MemberForm


def home(request):
    return render(request, 'home.html')


def band_list(request):
    """ A view of all bands. """
    bands = Band.objects.all()
    search = request.GET.get('search_box')
    if search:
        bands = bands.filter(name__icontains=search)
    return render(request, 'bands/band_list.html', {'bands': bands})


def band_contact(request):
    """ A example of form """
    if request.method == 'POST':
        form = BandContactForm(request.POST)
    else:
        form = BandContactForm()
    return render(request, 'bands/band_contact.html', {'form': form})


def band_detail(request, pk):
    """ A view of all members by bands. """
    band = Band.objects.get(pk=pk)
    members = Member.objects.all().filter(band=band)
    context = {'members': members, 'band': band}
    return render(request, 'bands/band_detail.html', context)


class BandCreate(CreateView):
    model = Band
    form_class = BandForm
    template_name = 'bands/band_form.html'
    success_url = reverse_lazy('bands')


class MemberCreate(CreateView):
    model = Member
    form_class = MemberForm
    template_name = 'bands/member_form.html'
    success_url = reverse_lazy('bands')


@login_required(login_url='/accounts/login/')
def protected_view(request):
    """ A view that can only be accessed by logged-in users """
    return render(request, 'bands/protected.html', {'current_user': request.user})


def message(request):
    """ Message if is not authenticated. Simple view! """
    return HttpResponse('Access denied!')

myproject/bands/templates/bands/band_contact.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  <title>Band Contact</title>
{% endblock title %}

{% block content %}

  <style>
    span.required:after {
      content: "*";
      color: red;
    }
  </style>

  <h1>Send e-mail</h1>
  <form class="form" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function(){
      $('#id_cc_myself').removeClass('form-control');
    })
  </script>
{% endblock js %}

myproject/bands/templates/bands/band_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Member Listing</title>
{% endblock title %}

{% block content %}
    <h2>Members of {{ band.name }}</h2>
    <ul class="list-group">
        {% for member in members %}
            {% if member.instrument == 'v' %}
                <li class="list-group-item list-group-item-info">
            {% else %}
                <li class="list-group-item">
            {% endif %}
                    {{ member.name }} - {{ member.get_instrument_display }}
                </li>
        {% endfor %}
    </ul>
{% endblock content %}

myproject/bands/templates/bands/band_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  <title>Band Form</title>
{% endblock title %}

  <style>
  span.required:after {
    content: "*";
    color: red;
  }
  </style>

{% block content %}

  <h1>Create band</h1>
  <form class="form col-sm-4" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
          {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
          {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function(){
      $('#id_can_rock').removeClass('form-control');
    })
  </script>
{% endblock js %}

myproject/bands/templates/bands/band_list.html
{% extends "base.html" %}

{% block title %}
    <title>Band List</title>
{% endblock title %}

{% block content %}
    <!-- search form -->
    <form class="navbar-form navbar-right" action="." method="get">
        <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>

    <h1>All Bands</h1>
    {% for band in bands %}
        <ul class="list-group">
          <li class="list-group-item">
            <span class="badge">{{ band.get_members_count }}</span>
            <h4><a href="{{ band.get_absolute_url }}">{{ band.name }}</a></h4>
            {% if band.can_rock %}
                <p>This band can rock!</p>
            {% endif %}
          </li>
        </ul>
    {% endfor %}
{% endblock content %}

myproject/bands/templates/bands/member_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  <title>Member Form</title>
{% endblock title %}

  <style>
  span.required:after {
    content: "*";
    color: red;
  }
  </style>

{% block content %}

  <h1>Create member</h1>
  <form class="form col-sm-4" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }} </span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
          {% for error in field.errors %}
            <span class="text-muted">{{ error }}</span>
          {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function(){
      $('#id_can_rock').removeClass('form-control');
    })
  </script>
{% endblock js %}

myproject/bands/templates/bands/protected.html
{% extends "base.html" %}

{% block title %}
    <title>Protected</title>
{% endblock title %}

{% block content %}
    <h1>Protected page</h1>

    <p>Logged as: {{ user }}</p>
{% endblock content %}

myproject/bands/templates/base.html
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" href="http://s3.amazonaws.com/snaaakes-static/img/colophon/django.png">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <!-- Font-awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

  {% block title %}
    <title>Django 2.1.7</title>
  {% endblock title %}

  <style>
    body {
      padding-top: 70px;
    }
  </style>

</head>

<body>

  {% include "menu.html" %}

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

    <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <!-- Bootstrap core JS -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  {% block js %}{% endblock js %}

</body>
</html>

myproject/bands/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Bem vindo ao site!</h1>
    <p>Este site é um exemplo da introdução ao <a href="https://www.djangoproject.com">Django</a> que está escrito em <a href="https://www.djangoproject.com/start/">Intro to Django</a>.</p>
</div>
{% endblock content %}

myproject/bands/templates/menu.html
<!-- Menu -->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="{% url 'home' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bands' %}">Bands</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'protected' %}">Protected</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Login</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Create</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="{% url 'band_form' %}">Create band</a>
          <a class="dropdown-item" href="{% url 'member_form' %}">Create member</a>
        </div>
      </li>
    </ul>
  </div>
</nav>